# Dockerfile.dev
# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the React app runs on (default is 3000)
EXPOSE 5173

# Define the command to run the application
CMD ["npm", "run", "dev"]